language: php
php:
    - 7.1
    - 7.2
before_script:
    - composer install --no-interaction
script:
    - wget https://link.zlatanstajic.com/software/php-library/outsource.zip
    - unzip outsource.zip
    - composer update
    - vendor/bin/phpcs index.php --standard='ruleset.xml' --colors
    - vendor/bin/phpcs src --standard='ruleset.xml' --colors
    - vendor/bin/phpcs tests --standard='ruleset.xml' --colors
    - vendor/bin/phpstan analyse src --level max
    - vendor/bin/phpunit
    - vendor/bin/phpunit --coverage-clover tests/logs/clover.xml
after_script:
    - php vendor/bin/coveralls -v