language: php
sudo: required
dist: trusty
group: edge
php:
  - 7.3
  - 7.4
install:
  - travis_retry composer install --no-interaction --no-suggest
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
before_script:
  - sudo mkdir -p /var/run/mysqld
  - sudo mkdir -p build/logs
  - sudo chmod -R 0777 build/logs
  - git clone https://github.com/php-library-league/shell.git
  - ls -al
script:
  - bash shell/outsource-install.sh
  - bash shell/auto-test.sh
after_success:
  - travis_retry php coveralls.phar -v
  - bash <(curl -s https://codecov.io/bash)
branches:
  only: master
cache:
  directories:
  - vendor
  - $HOME/.cache/composer
